"""Edit model details

Revision ID: 102f39f78bb6
Revises: 1cecec6ff614
Create Date: 2022-02-16 21:56:31.647008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102f39f78bb6'
down_revision = '1cecec6ff614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('riders', sa.Column('profile_pic_path', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('riders', 'profile_pic_path')
    op.drop_column('riders', 'location')
    # ### end Alembic commands ###
