"""Edit model details

Revision ID: 1cecec6ff614
Revises: 394407aa8512
Create Date: 2022-02-16 21:53:15.475303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cecec6ff614'
down_revision = '394407aa8512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'review',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('riders', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('riders', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('riders', 'password_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('riders', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('riders', 'number_plate',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('riders_email_key', 'riders', type_='unique')
    op.drop_constraint('riders_username_key', 'riders', type_='unique')
    op.create_index(op.f('ix_riders_email'), 'riders', ['email'], unique=True)
    op.create_index(op.f('ix_riders_username'), 'riders', ['username'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_riders_username'), table_name='riders')
    op.drop_index(op.f('ix_riders_email'), table_name='riders')
    op.create_unique_constraint('riders_username_key', 'riders', ['username'])
    op.create_unique_constraint('riders_email_key', 'riders', ['email'])
    op.alter_column('riders', 'number_plate',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('riders', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('riders', 'password_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('riders', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('riders', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('reviews', 'time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('reviews', 'rider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'review',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
