"""Initial migration

Revision ID: 394407aa8512
Revises: 
Create Date: 2022-02-16 16:40:47.432488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394407aa8512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('riders_location_key', 'riders', type_='unique')
    op.drop_column('riders', 'profile_pic_path')
    op.drop_column('riders', 'location')
    op.drop_constraint('users_location_key', 'users', type_='unique')
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_location_key', 'users', ['location'])
    op.add_column('riders', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('riders', sa.Column('profile_pic_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('riders_location_key', 'riders', ['location'])
    # ### end Alembic commands ###
